[meta]
name = "Author Time Check"
author = "TheJaZed"
category = "Game"
version = "0.4"
siteid = 769

[script]
dependencies = [ "NadeoServices", "MLFeedRaceData", "MLHook" ]
module = "AT_Check"
exports = [ "src/Export.as" ]